version: "3.3"

services:
  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # Force publishing on the 'elk' overlay
    networks:
      - elk

  kibana:
    image: kibana:7.14.1
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
