version: "3.3"

services:
  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay
    networks:
      - elk

  kibana:
    image: kibana:7.14.1
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
